CREATE TABLE ACC_CASH_ORDER_DETAIL
(
   ID_CASH_ORDER_DETAIL          INT PRIMARY KEY
  ,ID_CASH_ORDER                 INT NOT NULL
  ,VALID                         BOOLEAN NOT NULL
  ,ID_SALES_ORG					 INT NOT NULL
  ,DS_DOCUMENT_NUMBER			 NVARCHAR(16) NOT NULL
  ,MT_PREVIOUS_AMOUNT            NUMERIC(15, 6) NOT NULL
  ,MT_PREVIOUS_UNCLOSED_AMOUNT   NUMERIC(15, 6) NOT NULL
  ,MT_PAID_AMOUNT                NUMERIC(15, 6) NOT NULL
  ,DS_UNIQUE_KEY                 CHAR(36) NOT NULL
  ,DS_INVOICE_NUMBER             NVARCHAR(16)
)