CREATE TABLE ACC_TAX_MATRIX
(
   ID_TAX_MATRIX                INT PRIMARY KEY
  ,DS_CUSTOMER_CLASSIFICATION   NVARCHAR(25)
  ,DS_PRODUCT_CLASSIFICATION    NVARCHAR(25)
  ,MT_TAX_RATE                  NUMBER(5, 2)
)