CREATE TABLE ACC_OPEN_ITEM
(
   ID_OPEN_ITEM         INT PRIMARY KEY
  ,ID_SALES_ORG         INT NULL
  ,ID_CUSTOMER          INT NOT NULL
  ,ID_MAIN_CUSTOMER     INT NULL
  ,ID_AGENT             INT NULL
  ,DS_AGENT				NVARCHAR(160)
  ,DS_DOCUMENT_NUMBER   NVARCHAR(16)
  ,DS_INVOICE_NUMBER    NVARCHAR(16)
  ,ID_CONTRACT          INT NULL
  ,DT_POSTED            DATETIME
  ,DT_DUE               DATETIME
  ,MT_AMOUNT            NUMERIC(10, 2) NULL
  ,MT_UNCLOSED_AMOUNT   NUMERIC(10, 2) NULL
  ,FL_ALLOW_CORRECTION  BOOLEAN NOT NULL
)