CREATE TABLE ACC_CASH_ORDER
(
   ID_CASH_ORDER          INT PRIMARY KEY
  ,DT_CASH_ORDER          DATETIME NOT NULL
  ,DS_DOCUMENT_NUMBER     NVARCHAR(50)
  ,ID_CASH_ORDER_STATUS   INT NOT NULL
  ,ID_CASH_ORDER_OWNER    INT NOT NULL
  ,MT_AMOUNT_RECEIVED     NUMERIC(15, 6) NOT NULL
  ,DS_UNIQUE_KEY          CHAR(36) NOT NULL
  ,VR_FL_SENT             BOOLEAN NOT NULL
  ,ID_AGENT               INT NOT NULL
  ,VR_DT_CASH_ORDER       DATETIME NOT NULL
)