CREATE TABLE APP_PARAMETER
(
   ID_PARAMETER		INTEGER PRIMARY KEY AUTOINCREMENT
  ,DS_KEY        	NVARCHAR(50)
  ,DS_VALUE      	NVARCHAR(80)
  ,MT_VALUE      	INT64
  ,DT_VALUE      	DATETIME
  ,FL_INTERNAL   	BOOLEAN DEFAULT 0
)