
CREATE TABLE CSH_TASK
(
   ID_CASH_TASK			INT PRIMARY KEY
  ,ID_VISIT				INT NOT NULL
  ,ID_TASK_SORT			INT NOT NULL
  ,DS_TASK_VID			VARCHAR(100) NULL
  ,DS_ERP_TASK			VARCHAR(100) NULL
  ,MT_TASK_AMOUNT		NUMERIC(15, 2) NOT NULL
  ,DS_TASK_NOTE			VARCHAR(100) NULL
  ,ID_TASK_STATUS		INT NOT NULL DEFAULT 0
)