CREATE TABLE CSH_INVOICE_DETAIL
(
   ID_INVOICE_DETAIL			INT PRIMARY KEY
  ,ID_CASH_INVOICE				INT NOT NULL
  ,ID_ITEM_SORT					INT NOT NULL
  ,ID_ITEM						NUMERIC(15) NOT NULL
  ,DS_ITEM_NAME			      	VARCHAR(100) NULL
  ,MT_ITEM_PRICE				NUMERIC(15, 2) NOT NULL
  ,MT_ITEM_QUANTITY				NUMERIC(6) NOT NULL
  ,DS_ITEM_MEASURE_UNIT			VARCHAR(100) NULL
  ,MT_ADJUSTMENT_PERCENT		NUMERIC(15, 2) NULL
  ,MT_ITEM_VAT					NUMERIC(15, 6) NOT NULL
)