CREATE TABLE CSH_INVOICE
(
   ID_CASH_INVOICE				INT PRIMARY KEY
  ,ID_VISIT						INT NOT NULL
  ,DS_ERP_INVOICE				VARCHAR(100) NULL
  ,DT_INVOICE			      	DATETIME NULL
  ,DS_INVOICE_CUSTOMER_NAME		VARCHAR(100) NULL
  ,FL_INVOICE_ALLOW_CORRECTION	BOOLEAN DEFAULT 0 NOT NULL
  ,ID_INVOICE_STATE				INT NOT NULL DEFAULT 0
)