CREATE TABLE CUS_CUSTOMER_REQUEST
(
   ID_CUSTOMER_REQUEST          INT PRIMARY KEY
  ,VALID						BOOLEAN DEFAULT 1 NOT NULL
  ,ID_CUSTOMER                  INT NOT NULL
  ,DT_REQUEST                   DATE NOT NULL
  ,ID_USER                      INT NOT NULL
  ,DS_USER                      NVARCHAR(100) NULL
  ,ID_ROUTE                     INT NOT NULL  
  ,DS_ROUTE                     NVARCHAR(100) NULL
  ,ID_APPROVAL_STATUS			INT NOT NULL
  ,ID_TSM                       INT NULL
  ,DS_TSM                       NVARCHAR(100) NULL
  ,DT_TSM_APPROVED              DATE NULL
  ,ID_TSM_APPROVAL_STATUS		INT NULL
  ,ID_RSM                       INT NULL
  ,DT_RSM_APPROVED              DATE NULL
  ,ID_RSM_APPROVAL_STATUS		INT NULL
  ,FL_TSM_APPROVAL_NEED         BOOLEAN DEFAULT 0 NOT NULL
  ,FL_RSM_APPROVAL_NEED         BOOLEAN DEFAULT 0 NOT NULL
  ,DS_UNIQUE_KEY                NVARCHAR(36) NOT NULL
  ,FL_WEB						BOOLEAN DEFAULT 0 NOT NULL
  ,VR_FL_SENT                   BOOLEAN DEFAULT 0 NOT NULL
)