CREATE TABLE CUS_ROUTE_BUSINESS_TYPE_DETAIL
(
   ID_ROUTE_BUSINESS_TYPE_DETAIL   INT PRIMARY KEY
  ,ID_ROUTE						   INT NOT NULL  
  ,ID_BUSINESS_CATEGORY1           INT
  ,ID_CATEGORY3                    INT
)