CREATE TABLE CUS_CUSTOMER_CREDIT
(
   ID_CUSTOMER_CREDIT       INT PRIMARY KEY
  ,ID_CUSTOMER              INT NOT NULL
  ,DS_CREDIT_CONTROL_AREA   NVARCHAR(20) NULL
  ,MT_CREDIT_LIMIT          NUMERIC(10, 2) NULL
  ,MT_EXPOSURE              NUMERIC(10, 2) NULL
)