CREATE TABLE CUS_VISIT_LIST
(
   ID_VISIT_LIST   BIGINT PRIMARY KEY
  ,ID_VISIT_PLAN   BIGINT NOT NULL
  ,ID_SALES_ORG    INT NOT NULL
  ,ID_ROUTE        INT NOT NULL
  ,ID_AGENT        INT NOT NULL
  ,ID_AGENT_BACKUP INT NULL
  ,DT_VISIT        DATE NOT NULL
)