CREATE TABLE CUS_COVERAGE
(
   ID_COVERAGE              INT PRIMARY KEY
  ,ID_COVERAGE_TYPE         INT NOT NULL
  ,ID_COVERAGE_PK           INT NOT NULL  
  ,ID_Y_LEVEL               INT NULL
  ,ID_Y_HIERARCHY           INT NULL
  ,ID_DISTRICT              INT NULL
  ,ID_DEALER_TYPE           INT NULL
  ,ID_DEALER                INT NULL
  ,ID_MAIN_CUSTOMER         INT NULL
  ,ID_CUSTOMER              INT NULL
  ,ID_CHANNEL1              INT NULL
  ,ID_CHANNEL2              INT NULL
  ,ID_CHANNEL3              INT NULL
  ,ID_CHANNEL4              INT NULL
  ,ID_GROUP_CODE1           INT NULL
  ,ID_GROUP_CODE2           INT NULL
  ,ID_GROUP_CODE3           INT NULL
  ,ID_GROUP_CODE4           INT NULL
  ,ID_GROUP_CODE5           INT NULL
  ,ID_GROUP_CODE6           INT NULL
  ,ID_GROUP_CODE7           INT NULL
  ,ID_GROUP_CODE8           INT NULL
  ,ID_GROUP_CODE9           INT NULL
  ,MT_MULTI_SELECT1         INT NULL
  ,MT_MULTI_SELECT2         INT NULL
  ,MT_MULTI_SELECT3         INT NULL
  ,MT_MULTI_SELECT4         INT NULL
  ,MT_MULTI_SELECT5         INT NULL
  ,MT_MULTI_SELECT6         INT NULL
  ,MT_MULTI_SELECT7         INT NULL
  ,MT_MULTI_SELECT8         INT NULL
  ,MT_MULTI_SELECT9         INT NULL
  ,ID_CUSTOMER_TYPE         INT NULL
  ,ID_CUSTOMER_LIST         INT NULL
  ,FL_EXCLUDE               BOOLEAN DEFAULT 0
  ,ID_ROUTE_BUSINESS_TYPE   INT NULL
  ,ID_ROUTE_CHANNEL_TYPE    INT NULL
  ,ID_ROUTE                 INT NULL
  ,ID_SALES_ORG             INT NULL
  ,ID_SALES_OFFICE          INT NULL
  ,ID_CITY                  INT NULL
)