CREATE TABLE CUS_PRODUCT_EXCLUSION
(
   ID_PRODUCT_EXCLUSION   INT PRIMARY KEY
  ,ID_DEALER              INT
  ,ID_ROUTE               INT
  ,ID_CUSTOMER            INT
  ,ID_SALES_OFFICE        INT
)