CREATE TABLE CUS_CUSTOMER_REQUEST_DETAIL
(
   ID_CUSTOMER_REQUEST_DETAIL		INT PRIMARY KEY
  ,ID_CUSTOMER_REQUEST				INT NOT NULL
  ,ID_REQUEST_ATTRIBUTE				INT NOT NULL
  ,DS_OLD_VALUE						NVARCHAR(200) NULL
  ,DS_NEW_VALUE						NVARCHAR(200) NULL
  ,DS_UNIQUE_KEY					NVARCHAR(36) NOT NULL
  ,VR_FL_SENT						BOOLEAN DEFAULT 0 NOT NULL
  ,DS_UPDATED_RECORD_UNIQUE_KEY		NVARCHAR(36) NULL
)