CREATE TABLE CUS_PRODUCT_EXCLUSION_DETAIL
(
   ID_PRODUCT_EXCLUSION_DETAIL   INT PRIMARY KEY
  ,ID_PRODUCT_EXCLUSION          INT
  ,ID_PRODUCT                    INT
  ,DT_VALID_FROM                 DATE
  ,DT_VALID_TO                   DATE
)