CREATE TABLE CUS_VISIT_TYPE_ROUTE_CHANNEL
(
   ID_VISIT_TYPE_ROUTE_CHANNEL    INT PRIMARY KEY
  ,ID_VISIT_TYPE           INT NOT NULL
  ,ID_ROUTE_CHANNEL_TYPE   INT NOT NULL
  ,FL_DEFAULT				BOOLEAN DEFAULT 0 NOT NULL
  ,ID_FACE_CALL   INT NULL
)