CREATE TABLE CUS_CUSTOMER_TELEPHONE
(
   ID_CUSTOMER_TELEPHONE   INT PRIMARY KEY
  ,VALID                   BOOLEAN NOT NULL
  ,ID_SALES_ORG            INT NOT NULL
  ,ID_CUSTOMER             INT NOT NULL
  ,ID_TELEPHONE_TYPE       INT NOT NULL
  ,DS_TELEPHONE            NVARCHAR(30) NOT NULL
  ,DS_COMMENT              NVARCHAR(80) NULL  
  ,DS_UNIQUE_KEY           NVARCHAR(36) NULL
  ,FL_ERP                  BOOLEAN DEFAULT 0 NOT NULL
  ,FL_WEB                  BOOLEAN DEFAULT 0 NOT NULL
  ,VR_FL_SENT              BOOLEAN DEFAULT 0 NOT NULL
)