CREATE TABLE CUS_VISIT_PLAN
(
   ID_VISIT_PLAN			BIGINT PRIMARY KEY
  ,ID_SALES_ORG         	INT NULL
  ,ID_ROUTE					INT NOT NULL
  ,ID_AGENT					INT  NULL
  ,DT_VALID_FROM			DATE NULL
  ,DT_VALID_TO				DATE NULL
)