CREATE TABLE CUS_CONTRACT_CUSTOMER
(
   ID_CONTRACT_CUSTOMER   INT PRIMARY KEY
  ,ID_CONTRACT            INT NULL
  ,ID_CUSTOMER            INT NULL
  ,FL_PAYER               BOOLEAN
  ,ID_PAYMENT_TYPE        INT NULL
)