CREATE TABLE CUS_DEALER
(
   ID_DEALER                  INT PRIMARY KEY
  ,ID_DEALER_TYPE             INT NOT NULL
  ,ID_DISTRICT                INT NOT NULL
  ,ID_MEM_DEFAULT_WAREHOUSE   INT NULL
  ,DS_PARAMETER               NVARCHAR(20) NOT NULL
  ,ID_TAX_REGION              INT
)