CREATE TABLE CUS_CUSTOMER_NOTE
(
   ID_CUSTOMER_NOTE   INT PRIMARY KEY
  ,DT_UPDATE          DATETIME NOT NULL
  ,ID_USER            INT NOT NULL
  ,ID_CUSTOMER        INT NOT NULL
  ,DS_NOTE            NVARCHAR(1000) NULL
  ,DS_USER            NVARCHAR(200) NULL
  ,DS_UNIQUE_KEY      NVARCHAR(36) NOT NULL
  ,DT_DATE			  DATETIME NOT NULL
  ,FL_READ			  BOOLEAN DEFAULT 0 NOT NULL
  ,VR_FL_SENT         BOOLEAN DEFAULT 0 NOT NULL
  ,ID_SOURCE	      INT NULL
)