CREATE TABLE CUS_VISIT_TYPE
(
   ID_VISIT_TYPE			INT PRIMARY KEY
  ,DS_VISIT_TYPE         	NVARCHAR(50) NULL
  ,DS_ERP_CODE				NVARCHAR(30) NULL  
  ,FL_ORDER_MANDATORY	    BOOLEAN DEFAULT 0 NOT NULL
  ,FL_AUDIT_VISIT		    BOOLEAN DEFAULT 0 NOT NULL
  ,FL_CERTIFICATION_VISIT	BOOLEAN DEFAULT 0 NOT NULL
  ,FL_WORKWITH_VISIT		BOOLEAN DEFAULT 0 NOT NULL
)