CREATE TABLE CUS_REQUEST_ATTRIBUTE
(
   ID_REQUEST_ATTRIBUTE				INT PRIMARY KEY
  ,DS_REQUEST_ATTRIBUTE				NVARCHAR(50) NULL
  ,FL_TSM_APPROVAL_NEED				BOOLEAN NOT NULL
  ,FL_RSM_APPROVAL_NEED				BOOLEAN NOT NULL
)