CREATE TABLE CUS_CONTRACT
(
   ID_CONTRACT              INT PRIMARY KEY
  ,ID_SALES_ORG             INT
  ,FL_ACTIVE			    BOOLEAN
  ,DT_VALID_FROM            DATE
  ,DT_VALID_TO              DATE
  ,DS_ERP_CODE              NVARCHAR(20)
  ,DS_COMMERCIAL_CONTRACT   NVARCHAR(20)
  ,DS_CREDIT_CONTROL_AREA   NVARCHAR(10)
  ,ID_PRICE_LIST_TYPE       INT
  ,MT_DUE_DAYS              INT
  ,DS_PRICE_LIST_TYPE       NVARCHAR(100)
)