CREATE TABLE CUS_CUSTOMER_ATTRIBUTE
(
   ID_CUSTOMER_ATTRIBUTE       INT PRIMARY KEY
  ,FL_ACTIVE                   BOOLEAN DEFAULT 0
  ,ID_CUSTOMER                 INT NOT NULL
  ,ID_SALES_ORG                INT NOT NULL
  ,ID_SALES_OFFICE             INT NULL
  ,ID_GROUP_CODE1              INT NULL
  ,ID_GROUP_CODE2              INT NULL
  ,ID_GROUP_CODE3              INT NULL
  ,ID_GROUP_CODE4              INT NULL
  ,ID_GROUP_CODE5              INT NULL
  ,MT_MULTI_SELECT1            INT NULL
  ,MT_MULTI_SELECT2            INT NULL
  ,MT_MULTI_SELECT3            INT NULL
  ,MT_MULTI_SELECT4            INT NULL
  ,MT_MULTI_SELECT5            INT NULL
  ,FL_BLOCKED_FOR_ORDER        BOOLEAN DEFAULT 0 NOT NULL
  ,ID_CUSTOMER_SALES_UNIT      INT NULL
  ,ID_CUSTOMER_SALES_GROUP     INT NULL
  ,DS_VIRTUAL_BUSINESS_TYPE    NVARCHAR(50) NULL
  ,DS_BUSINESS_INITIATIVE_NO   NVARCHAR(2) NULL
)