CREATE TABLE CUS_ROUTE
(
   ID_ROUTE                     INT PRIMARY KEY
  ,DS_ROUTE                     NVARCHAR(100) NOT NULL
  ,ID_HIERARCHY                 INT NULL
  ,ID_SALES_ORG                 INT NOT NULL
  ,DS_SALES_ORG_ERP_CODE        NVARCHAR(20) NULL
  ,ID_ROUTE_BUSINESS_TYPE       INT NOT NULL
  ,ID_ROUTE_CHANNEL_TYPE        INT NOT NULL
  ,FL_HAS_MULTIPLE_VISIT_TYPE   BOOLEAN DEFAULT 0 NOT NULL
  ,ID_FACE_CALL                 INT NULL
  ,MT_UTC_OFFSET				INT NULL
  ,DS_ERP_CODE                  NVARCHAR(16) NULL
  ,ID_ROUTE_COVERAGE            INT NULL
  ,FL_CAN_SEE_OTHERS			BOOLEAN DEFAULT 0 NOT NULL
  ,FL_OTHERS_CAN_SEE			BOOLEAN DEFAULT 0 NOT NULL
)