CREATE TABLE MEM_ORDER_HEADER
(
   ID_ORDER       INT NOT NULL
  ,ID_DEALER      INT
  ,DT_ORDER       DATETIME NULL
  ,DT_SHIPMENT    DATETIME NULL
  ,ID_STATUS      SMALLINT NULL
  ,ID_CUSTOMER    INT NULL
  ,ID_MAIN_CUSTOMER    INT NULL
  ,ID_AGENT       INT NULL
  ,ID_ROUTE       INT NULL
  ,ID_WAREHOUSE   INT NULL
  ,DS_COMMENT     NVARCHAR(200) NULL
  ,DS_UNIQUE_KEY  NVARCHAR(36) NOT NULL
  ,VR_FL_SENT     SMALLINT DEFAULT 0
  ,FL_FROM_WEB	  INT NULL
) 