CREATE TABLE MEM_REQUEST_HEADER
(
   ID_REQUEST_HEADER				INTEGER PRIMARY KEY
  ,ID_PK							INT
  ,DT_CREATION						DATETIME NULL
  ,DT_ACTION						DATETIME NULL
  ,ID_CUSTOMER_SOURCE				INT
  ,DS_CUSTOMER_SOURCE				NVARCHAR(200)
  ,DS_CUSTOMER_SOURCE_ADDRESS		NVARCHAR(200)
  ,ID_CUSTOMER_TARGET				INT NULL
  ,DS_CUSTOMER_TARGET				NVARCHAR(200) NULL
  ,DS_CUSTOMER_TARGET_ADDRESS		NVARCHAR(200) NULL
  ,ID_ROUTE							INT NULL
  ,ID_REPAIR_REASON					INT NULL
  ,ID_ERP_STATUS					INT NULL 
  ,DS_ERP_STATUS					NVARCHAR(40) NULL
  ,ID_REQUEST_TYPE					INT
  ,DS_REQUEST_TYPE					NVARCHAR(40) NULL
  ,ID_APPROVAL_STATUS				INT NULL
  ,DS_APPROVAL_STATUS				NVARCHAR(80) NULL
  ,DS_USER_CREATED					NVARCHAR(100) NULL
  ,ID_APPROVAL_STATUS_NEW			INT NULL
  ,FL_FROM_WEB						INT NULL
  ,DS_UNIQUE_KEY		 CHAR(36) NULL
  ,VR_FL_SENT            BOOLEAN DEFAULT 0 NOT NULL
)