CREATE TABLE MEM_CUSTOMER_INVENTORY
(
   ID_CUSTOMER_INVENTORY   INT PRIMARY KEY
  ,ID_ROUTE                INT NOT NULL
  ,ID_CUSTOMER             INT NOT NULL
  ,ID_MAIN_CUSTOMER        INT NULL
  ,ID_MEM                  INT NOT NULL
  ,DS_BARCODE              NVARCHAR(8) NOT NULL
  ,DS_SERIAL               NVARCHAR(20) NULL
  ,ID_MODEL                INT NULL
  ,ID_LOGO_TYPE            INT NULL
  ,DS_OWNER_ERP_CODE	   NVARCHAR(20) NULL
)