CREATE TABLE MEM_MOVEMENT
(
   ID_MOVEMENT		     INT
  ,DT_MOVEMENT			 DATETIME NULL
  ,ID_CUSTOMER_SOURCE	 INT
  ,ID_CUSTOMER_TARGET	 INT
  ,ID_ROUTE			     INT
  ,ID_MEM			     INT
  ,ID_ERP_STATUS	     INT
)