CREATE TABLE MEM_REQUEST_DETAIL
(
   ID_PK_HEADER			INT
  ,ID_MEM               INT
  ,ID_REQUEST_TYPE	    INT
  ,DS_BARCODE           NVARCHAR(40) NULL
  ,DS_MODEL             NVARCHAR(40) NULL
  ,DS_CLASS             NVARCHAR(40) NULL
  ,DS_CATEGORY          NVARCHAR(40) NULL
  ,DS_LOGO_TYPE         NVARCHAR(40) NULL
)