CREATE TABLE MEM_AUDIT
(
   ID_AUDIT      INT PRIMARY KEY
  ,DT_AUDIT      DATETIME NULL
  ,ID_AGENT		 INT
  ,ID_DEALER	 INT
  ,ID_ROUTE		 INT
  ,ID_CUSTOMER   INT
  ,ID_VISIT      INT
  ,DS_COMMENT    NVARCHAR(100)
  ,DS_UNIQUE_KEY NVARCHAR(36)
  ,VR_FL_SENT    SMALLINT DEFAULT 0
  ,VALID         BOOLEAN NOT NULL
)