CREATE TABLE MEM_AUDIT_DETAIL
(
   ID_AUDIT_DETAIL       INT PRIMARY KEY
  ,ID_AUDIT              INT
  ,ID_MEM                INT NULL
  ,DS_COMMENT            NVARCHAR(100)
  ,DS_BARCODE            NVARCHAR(8)
  ,DS_SERIAL             NVARCHAR(20)
  ,ID_MODEL              INT NULL
  ,ID_LOGO_TYPE          INT NULL
  ,DS_BARCODE_ACTUAL     NVARCHAR(8)
  ,DS_SERIAL_ACTUAL      NVARCHAR(20)
  ,ID_MODEL_ACTUAL       INT NULL
  ,ID_LOGO_TYPE_ACTUAL   INT NULL
  ,ID_RESULT             SMALLINT NULL
  ,MT_REMARK             SMALLINT NULL
  ,ID_PROBLEM            SMALLINT NULL
  ,ID_REPAIR_REASON      SMALLINT NULL
  ,ID_CUSTOMER_TARGET    INT NULL
  ,ID_MAIN_CUSTOMER_TARGET    INT NULL
  ,DT_MOVEMENT			 DATETIME NULL
  ,DS_MOVEMENT_COMMENT   NVARCHAR(250)
  ,FL_OFF_ROUTE          BOOLEAN NOT NULL
  ,FL_SCAN_MANDATORY     BOOLEAN NOT NULL
  ,FL_BARCODE_MANUAL     BOOLEAN NOT NULL
  ,DT_PICKUP_DATE		 DATETIME NULL
  ,DS_CONTACT_NAME       NVARCHAR(50)
  ,DS_CONTACT_PHONE      NVARCHAR(30)
  ,ID_BARCODE_ACTION     INT NULL
  ,VALID                 BOOLEAN NOT NULL
)