CREATE TABLE ORD_ORDER_DETAIL
(
   ID_ORDER_DETAIL                  INT PRIMARY KEY
  ,ID_ORDER                         INT NOT NULL
  ,ID_ORDER_DETAIL_TYPE             SMALLINT NOT NULL
  ,MT_SEQUENCE                      SMALLINT NOT NULL
  ,ID_PRODUCT                       INT NOT NULL
  ,ID_RECIPE_PRODUCTION             INT
  ,ID_UNIT                          SMALLINT NOT NULL
  ,MT_QUANTITY                      NUMERIC(6, 2)
  ,MT_QUANTITY_SHIPPED              NUMERIC(6, 2)
  ,MT_QUANTITY_BILLED               NUMERIC(6, 2)
  ,MT_PRICE_UNIT                    NUMERIC(15, 6)
  ,MT_PRICE_UNIT_WITH_VAT           NUMERIC(15, 6)
  ,MT_PRICE_UNIT_SPD                NUMERIC(15, 6)
  ,MT_PRICE_UNIT_SPD_WITH_VAT       NUMERIC(15, 6)
  ,MT_PRICE_GROSS                   NUMERIC(15, 6)
  ,MT_PRICE_GROSS_WITH_VAT          NUMERIC(15, 6)
  ,MT_PRICE_GROSS_SPD               NUMERIC(15, 6)
  ,MT_PRICE_GROSS_SPD_WITH_VAT      NUMERIC(15, 6)
  ,MT_DISCOUNT_PROMOTION            NUMERIC(15, 6)
  ,MT_DISCOUNT_PROMOTION_WITH_VAT   NUMERIC(15, 6)
  ,MT_DISCOUNT_CUSTOMER_RATE        NUMERIC(7, 4)
  ,MT_DISCOUNT_CUSTOMER             NUMERIC(15, 6)
  ,MT_DISCOUNT_CUSTOMER_WITH_VAT    NUMERIC(15, 6)
  ,MT_DISCOUNT_TOTAL                NUMERIC(15, 6)
  ,MT_DISCOUNT_TOTAL_WITH_VAT       NUMERIC(15, 6)
  ,MT_PRICE_NET                     NUMERIC(15, 6)
  ,MT_TAX_RATE                      NUMERIC(5, 2)
  ,MT_TAX_AMOUNT                    NUMERIC(15, 6)
  ,MT_TAX_AMOUNT_SPD                NUMERIC(15, 6)
  ,MT_WEIGHT_NET                    NUMERIC(8, 4)
  ,MT_WEIGHT_GROSS                  NUMERIC(8, 4)
  ,ID_CURRENCY                      SMALLINT
  ,DS_PROCESS_NO                    NVARCHAR(50)
  ,ID_ORDER_DETAIL_STATUS           SMALLINT
  ,ID_DETAIL_CANCEL_REASON          SMALLINT
  ,ID_RETURN_REASON                 SMALLINT
  ,DS_PROMO_INFO                    NVARCHAR(40)
  ,DS_NOTE                          NVARCHAR(40)
  ,VALID                            BOOLEAN NOT NULL
  ,DS_UNIQUE_KEY                    CHAR(36) NOT NULL
  ,VR_ID_PRODUCT_TYPE               SMALLINT
  ,VR_DS_PRODUCT_NO                 NVARCHAR(15)
  ,VR_DS_PRODUCT                    NVARCHAR(40)
  ,VR_DS_RETURN_REASON              NVARCHAR(40)
  ,VR_MT_QUANTITY_SMALL             NUMERIC(10, 3)
  ,CONSTRAINT UQ_DS_UNIQUE_KEY UNIQUE (DS_UNIQUE_KEY)
);

CREATE TRIGGER FUQ_ORDER_PRODUCT
BEFORE INSERT ON ORD_ORDER_DETAIL
FOR EACH ROW
WHEN (
    EXISTS (SELECT NULL
            FROM ORD_ORDER_DETAIL D
            WHERE D.ID_ORDER = NEW.ID_ORDER
			  AND D.ID_ORDER_DETAIL_TYPE = NEW.ID_ORDER_DETAIL_TYPE
			  AND D.ID_PRODUCT = NEW.ID_PRODUCT
			  AND D.VALID = 1)
)
BEGIN
  SELECT RAISE( ABORT, 'UNIQUE CONSTRAINT FAILED' );
END;