CREATE TABLE ORD_GROUP_CODE_VALUE
(
   ID_GROUP_CODE_VALUE		INT PRIMARY KEY
  ,ID_DEALER				INT NOT NULL
  ,DS_TITLE					NVARCHAR(30) NULL
  ,ID_CODE_VALUE          	INT NULL
  ,DS_VALUE					NVARCHAR(30) NULL
  ,MT_ORDER          		INT NULL
)