CREATE TABLE ORD_ORDER_DETAIL_PROMO
(
    ID_ORDER_DETAIL_PROMO           INT PRIMARY KEY
   ,ID_ORDER_DETAIL                 INT NOT NULL
   ,ID_ORDER                        INT NOT NULL
   ,ID_PROMOTION                    INT NOT NULL
   ,ID_PROMOTION_RULE               INT NOT NULL
   ,ID_PROMOTION_REWARD             INT NOT NULL
   ,MT_PROMOTION_RATE               NUMERIC(5, 2)
   ,MT_PROMOTION_AMOUNT             NUMERIC(15, 6)
   ,MT_PROMOTION_AMOUNT_WITH_VAT    NUMERIC(15, 6)
   ,MT_COMPANY_SHARE                NUMERIC(5, 2)
   ,MT_MAX_DISCOUNT_RATE            NUMERIC(5, 2)
   ,FL_FREE                         BOOLEAN NOT NULL
   ,FL_MONEY_DISCOUNT               BOOLEAN NOT NULL
   ,MT_TOTAL_MONEY_DISCOUNT         NUMERIC(15, 6)
   ,VALID                           BOOLEAN NOT NULL
   ,DS_UNIQUE_KEY                   CHAR(36) NOT NULL
   ,CONSTRAINT UQ_DS_UNIQUE_KEY UNIQUE(DS_UNIQUE_KEY)
)