CREATE TABLE PDA_PHOTO_ACTIVITY
(
   ID_PHOTO_ACTIVITY   INT PRIMARY KEY
  ,ID_CUSTOMER         INT NOT NULL
  ,ID_VISIT            INT NOT NULL
  ,DS_UNIQUE_KEY       NVARCHAR(36) NOT NULL
  ,VR_FL_SENT          BOOLEAN DEFAULT 0 NOT NULL
)