CREATE TABLE PDA_NO_GPS_REASON
(
   ID_NO_GPS_REASON     INT PRIMARY KEY
  ,DS_NO_GPS_REASON     NVARCHAR(50) NULL
  ,MT_ORDER             SMALLINT NULL
  ,FL_AUTOMATIC         BOOLEAN NOT NULL
  ,FL_PASSWORD_REQUIRED BOOLEAN NOT NULL
)