CREATE TABLE PDA_CUSTOMER_STATISTIC
(
   ID_CUSTOMER_STATISTIC    INT PRIMARY KEY
  ,ID_CUSTOMER              INT NOT NULL
  ,DT_PROCESS               DATE
  ,MT_PROCESS_ORDER         SMALLINT
  ,DS_SALES                 NVARCHAR(2000)
  ,DS_STOCK_BALANCE         NVARCHAR(4000)
)