CREATE TABLE PDA_VISIT_LOG
(
   ID_VISIT_LOG					    INT PRIMARY KEY
  ,ID_ACTION_TYPE     				INT NOT NULL
  ,ID_TIME_SOURCE      				INT NOT NULL
  ,MT_UTC_OFFSET					INT NULL
  ,FL_BLOCK_VISIT_REAL_TIME			BOOLEAN NULL
  ,MT_GPS_TIME						BIGINT NULL
  ,DT_SERVER_TIME					DATETIME NULL
  ,DT_DEVICE_TIME					DATETIME NOT NULL
  ,MT_SYSTEM_ELAPSED				BIGINT NOT NULL
  ,MT_SERVER_ELAPSED				BIGINT NOT NULL
  ,DS_VISIT_UNIQUE_KEY	   			NVARCHAR(36) NOT NULL
  ,DS_UNIQUE_KEY	   				NVARCHAR(36) NOT NULL
  ,VR_FL_SENT          				BOOLEAN DEFAULT 0 NOT NULL
)