CREATE TABLE PDA_VISIT
(
   ID_VISIT						    INT PRIMARY KEY
  ,ID_COMPANY          				INT NOT NULL
  ,ID_DEALER          				INT NOT NULL
  ,ID_USER						    INT NOT NULL    
  ,ID_CUSTOMER						INT NOT NULL
  ,ID_ROUTE            				INT NOT NULL
  ,ID_SALES_ORG        				INT NOT NULL
  ,ID_VISIT_LIST					BIGINT NULL
  ,ID_VISIT_LIST_DETAIL				BIGINT NULL
  ,ID_VISIT_TYPE					INT NULL
  ,DT_VISIT_START					DATETIME NULL
  ,DT_VISIT_START_REAL				DATETIME NULL
  ,DT_VISIT_END						DATETIME NULL
  ,DT_VISIT_END_REAL				DATETIME NULL
  ,ID_NO_SALES_REASON   			INT NULL
  ,MT_ORDER							NUMERIC(10,2) null 
  ,ID_NO_GPS_REASON    				INT NULL
  ,MT_LATITUDE         				NUMERIC(16, 12) NULL
  ,MT_LONGITUDE        				NUMERIC(16, 12) NULL
  ,MT_LATITUDE_END     				NUMERIC(16, 12) NULL
  ,MT_LONGITUDE_END    				NUMERIC(16, 12) NULL
  ,FL_EXCLUSIVE_GPS					BOOLEAN DEFAULT 0 NOT NULL
  ,MT_EXCLUSIVE_LATITUDE         	NUMERIC(16, 12) NULL
  ,MT_EXCLUSIVE_LONGITUDE        	NUMERIC(16, 12) NULL
  ,FL_COMPLETED  					BOOLEAN DEFAULT 1 NOT NULL
  ,MT_VISIT_DISTANCE				NUMERIC(10, 2) NULL
  ,FL_VIRTUAL_CUSTOMER				BOOLEAN DEFAULT 0 NOT NULL
  ,DS_UNIQUE_KEY	   				NVARCHAR(36) NOT NULL
  ,VR_FL_SENT          				BOOLEAN DEFAULT 0 NOT NULL
  ,ID_ACTIVITY	    				INT NULL
  ,DS_ACTIVITY_UNIQUE_KEY	   		NVARCHAR(36) NULL
  ,ID_ACTIVITY_DATE	    			INT NULL
  ,DS_ACTIVITY_DATE_UNIQUE_KEY	   	NVARCHAR(36) NULL
  --#20457: PROD PDA color indication for Visit List -- We are downloading last 7 days' visits. That's why this flag is added.
  ,FL_FROM_WEB						BOOLEAN DEFAULT 0 NOT NULL
)