CREATE TABLE POS_TRANSACTION_DETAIL
(
   ID_TRANSACTION_DETAIL    INT PRIMARY KEY
  ,ID_TRANSACTION			INT NOT NULL
  ,VALID					BOOLEAN DEFAULT 1 NOT NULL
  ,ID_PRODUCT				INT NOT NULL
  ,MT_QUANTITY				INT NULL
  ,DS_UNIQUE_KEY            NVARCHAR(36) NOT NULL 
)