CREATE TABLE POS_BALANCE
(
   ID_BALANCE                   INT PRIMARY KEY
  ,ID_PRODUCT					INT NOT NULL
  ,MT_QUANTITY					INT NOT NULL
  ,ID_CUSTOMER					INT NULL
  ,ID_MAIN_CUSTOMER             INT NULL
  ,ID_WAREHOUSE					INT NULL
)