CREATE TABLE PRD_PRICE_LIST
(
   ID_PRICE_LIST        INT PRIMARY KEY
  ,ID_PRICE_LIST_TYPE   INT NOT NULL
  ,ID_PRODUCT           INT NOT NULL
  ,ID_UNIT              INT NOT NULL
  ,MT_PRICE             NUMERIC(15, 6)
)