CREATE TABLE PRD_CATEGORY_MATRIX
(
   ID_CATEGORY_MATRIX   INT PRIMARY KEY
  ,ID_CATEGORY1         INT
  ,ID_CATEGORY2         INT
  ,ID_CATEGORY3         INT
  ,ID_CATEGORY4         INT
  ,ID_CATEGORY5         INT
  ,ID_CATEGORY6         INT
  ,ID_CATEGORY7         INT
)