CREATE TABLE PRD_ASSORTMENT_LIST_DETAIL
(
   ID_ASSORTMENT_LIST_DETAIL   INT PRIMARY KEY
  ,ID_ASSORTMENT_LIST          INT NOT NULL
  ,ID_PRODUCT                  INT NOT NULL
  ,DT_VALID_FROM               DATE NOT NULL
  ,DT_VALID_TO                 DATE NOT NULL
)