CREATE TABLE PRD_PRICE_DISCOUNT
(
   ID_PRICE_DISCOUNT   INT PRIMARY KEY
  ,ID_CHANNEL          INT
  ,ID_CITY             INT
  ,ID_PRODUCT          INT
  ,DT_VALID_FROM       DATETIME
  ,DT_VALID_TO         DATETIME
  ,MT_DISCOUNT_RATE    NUMERIC(10, 2)
)