CREATE TABLE PRD_ASSORTMENT_LIST
(
   ID_ASSORTMENT_LIST        INT PRIMARY KEY
  ,DS_ASSORTMENT_LIST        NVARCHAR(40) NULL
  ,ID_ASSORTMENT_LIST_TYPE   INT NOT NULL
  ,DT_VALID_FROM             DATE NOT NULL
  ,DT_VALID_TO               DATE NOT NULL
  ,ID_SALES_ORG              INT NULL
  ,ID_CHANNEL3               INT NULL
  ,ID_CUSTOMER_SALES_GROUP   INT NULL
  ,ID_SALES_OFFICE           INT NULL
  ,ID_S_HIERARCHY            INT NULL
  ,ID_CUSTOMER               INT NULL
  ,ID_Y_HIERARCHY            INT NULL
  ,DS_DESCRIPTION            NVARCHAR(50) NULL
)