CREATE TABLE PRM_PROMOTION_DISCOUNT
(
   ID_PROMOTION_DISCOUNT   INT PRIMARY KEY
  ,ID_PROMOTION            INT
  ,ID_DISCOUNT_GROUP       INT
  ,MT_DISCOUNT             NUMERIC(7, 4)
  ,DS_DISCOUNT             NVARCHAR(10)
  ,MT_COMPANY_SHARE        NUMERIC(5, 2)
)