CREATE TABLE PRM_PROMOTION_TYPE
(
   ID_PROMOTION_TYPE            INT PRIMARY KEY
  ,DS_PROMOTION_TYPE            NVARCHAR(50)
  ,ID_APPLICATION_MODE          INT
  ,DS_BLOCKED_PROMOTION_TYPES   NVARCHAR(50)
  ,FL_MULTIPLE                  BOOLEAN NOT NULL
  ,FL_CONSTANT                  BOOLEAN NOT NULL
  ,MT_APPLICATION_ORDER         INT
)