CREATE TABLE PRM_PROMOTION_RULE
(
   ID_PROMOTION_RULE        INT PRIMARY KEY
  ,ID_PROMOTION             INT NOT NULL
  ,FL_PROGRESSIVE           BOOLEAN
  ,MT_MIN_AMOUNT            INT
  ,ID_MIN_AMOUNT_CURRENCY   INT
  ,MT_MIN_QUANTITY          INT
  ,ID_MIN_QUANTITY_UNIT     INT
  ,MT_SEQUENCE              INT
)