CREATE TABLE PRM_PROMOTION_REWARD
(
   ID_PROMOTION_REWARD          INT PRIMARY KEY
  ,ID_PROMOTION_RULE            INT
  ,ID_PROMOTION                 INT
  ,ID_PRODUCT_GROUP             INT
  ,ID_PRODUCT                   INT
  ,MT_DISCOUNT                  NUMERIC(5, 2)
  ,MT_MAX_DISCOUNT              NUMERIC(5, 2)
  ,ID_UNIT                      INT
  ,MT_FREE_AMOUNT               INT
  ,DS_PARAMETER                 NVARCHAR(10)
  ,MT_COMPANY_SHARE             NUMERIC(5, 2)
  ,MT_DISCOUNT_REWARD_PERCENT   NUMERIC(5, 2)
  ,MT_DISCOUNT_REWARD_AMOUNT    NUMERIC(15, 2)
)