CREATE TABLE SEC_USER
(
   ID_USER               INT PRIMARY KEY
  ,ID_USER_ROLE          INT NOT NULL
  ,ID_COMPANY            INT NOT NULL
  ,ID_DEALER             INT NULL
  ,DS_USER               NVARCHAR(20) NULL
  ,DS_USER_DESCRIPTION		NVARCHAR(100) NULL
  ,DS_GPID					NVARCHAR(8) NULL
  ,DS_PASSWORD				NVARCHAR(100) NULL
  ,MT_PHOTO_COMPRESS_RATIO	INT NULL
  ,MT_MIN_PHOTO				INT NULL
  ,MT_MAX_PHOTO				INT NULL
  ,ID_PHOTO_QUALITY			INT NULL
  ,ID_USER_BACKUP			INT NULL
  ,ID_HIERARCHY				INT NULL
  ,FL_HIERARCHY				BOOLEAN NULL
  ,FL_BLOCK_VISIT_REAL_TIME	BOOLEAN NULL
  ,MT_PHOTO_STORAGE_PERIOD	INT NULL
  ,FL_LOCK_COMMENT			BOOLEAN NULL
  ,DS_LEGACY_NO             NVARCHAR(30) NULL
)