CREATE TABLE STO_CUSTOMER_BALANCE_DETAIL
(
   ID_CUSTOMER_BALANCE_DETAIL   INT NOT NULL
  ,ID_CUSTOMER_BALANCE          INT NOT NULL
  ,ID_PRODUCT                   INT NOT NULL
  ,ID_UNIT                      INT NOT NULL
  ,MT_SHELF_QUANTITY            NUMERIC(10, 3)
  ,VALID                        BOOLEAN NOT NULL
  ,DS_UNIQUE_KEY				CHAR(36) NOT NULL
)