CREATE TABLE STO_STOCK_BALANCE
(
   ID_STOCK_BALANCE     INT PRIMARY KEY
  ,ID_PRODUCT_UNIT		INT NOT NULL
  ,ID_WAREHOUSE         INT NOT NULL
  ,ID_PRODUCT           INT NOT NULL
  ,ID_UNIT				INT NOT NULL
  ,MT_MULTIPLIER        NUMERIC(10, 3)
)