CREATE TABLE SUR_AEP_EQUIPMENT
(
   ID_AEP_EQUIPMENT      INT PRIMARY KEY
  ,DS_AEP_EQUIPMENT      NVARCHAR(100) NOT NULL
  ,ID_AEP                INT NULL
  ,ID_SURVEY_CATEGORY    INT NULL
  ,FL_MANDATORY_ANSWER   BOOLEAN NOT NULL
  ,FL_FOR_ALL_COVERAGE   BOOLEAN NOT NULL
  ,ID_AEP_TYPE           INT NULL
)