CREATE TABLE SUR_INVOLVED_SURVEY
(
   ID_INVOLVED_SURVEY   INT PRIMARY KEY
  ,ID_CUSTOMER          INT NULL
  ,ID_SURVEY	        INT NULL
  ,DS_SURVEY            NVARCHAR(100) NOT NULL
  ,DT_ANSWER			DATE NULL
)