CREATE TABLE SUR_AEP_EQUIPMENT_DETAIL
(
   ID_AEP_EQUIPMENT_DETAIL   INT PRIMARY KEY
  ,ID_AEP_EQUIPMENT          INT NOT NULL
  ,ID_CUSTOMER               INT NULL
  ,ID_EQUIPMENT              INT NOT NULL
  ,DT_START                  DATE NOT NULL
  ,DT_END                    DATE NOT NULL
  ,DT_VISIBLE_START          DATE NOT NULL
  ,DT_VISIBLE_END            DATE NOT NULL
  ,DS_EQUIPMENT_POSITION     NVARCHAR(100) NOT NULL
)