CREATE TABLE SUR_EQUIPMENT
(
   ID_EQUIPMENT            INT PRIMARY KEY
  ,DS_EQUIPMENT            NVARCHAR(100) NOT NULL
  ,DS_SAP_EQUIPMENT_CODE   NVARCHAR(30) NOT NULL
  ,ID_EQUIPMENT_FORMAT     INT NOT NULL
  ,ID_SURVEY_CATEGORY      INT NULL
)