CREATE TABLE SUR_AEP_PLANOGRAM
(
   ID_AEP_PLANOGRAM            INT PRIMARY KEY
  ,DS_AEP_PLANOGRAM            NVARCHAR(100) NOT NULL
  ,ID_AEP                      INT NULL
  ,ID_SURVEY_CATEGORY          INT NULL
  ,DT_START                    DATE NOT NULL
  ,DT_END                      DATE NOT NULL
  ,FL_MANDATORY_ANSWER         BOOLEAN NOT NULL
  ,FL_MANDATORY_PHOTO_ANSWER   BOOLEAN NOT NULL
)