CREATE TABLE SUR_SURVEY_ANSWER
(
   ID_SURVEY_ANSWER     INT PRIMARY KEY
  ,ID_QUESTION          INT NULL
  ,ID_SURVEY			INT NULL
  ,ID_ANSWER            INT NULL
  ,DS_ANSWER            NVARCHAR(100) NULL
  ,MT_SCORE             INT NULL
  ,MT_DISPLAY_ORDER     INT NULL
  ,ID_AEP				INT NULL
)