CREATE TABLE TSM_TASK_PHOTO
(
   ID_TASK_PHOTO		INT PRIMARY KEY
  ,VALID				BOOLEAN DEFAULT 1 NOT NULL
  ,ID_TASK				INT NOT NULL
  ,DS_UNIQUE_KEY		NVARCHAR(36) NOT NULL
  ,VR_FL_SENT			BOOLEAN DEFAULT 0 NOT NULL
)