CREATE TABLE TSM_TASK
(
   ID_TASK								INT PRIMARY KEY
  ,VALID								BOOLEAN DEFAULT 1 NOT NULL
  ,DT_INSERT							DATETIME NOT NULL
  ,ID_USER_INSERT						INT NOT NULL
  ,DS_TASK								NVARCHAR(100) NOT NULL
  ,DS_DESCRIPTION						NVARCHAR(1000) NULL
  ,DT_DEADLINE							DATETIME NOT NULL
  ,FL_PHOTO_MANDATORY					BOOLEAN NOT NULL
  ,ID_TASK_CATEGORY						INT NULL
  ,ID_CUSTOMER							INT NULL
  ,DS_UNIQUE_KEY						NVARCHAR(36) NOT NULL
  ,DS_ACTIVITY_DATE_UNIQUE_KEY			NVARCHAR(36) NULL
  ,FL_WEB								BOOLEAN DEFAULT 0 NOT NULL
  ,VR_FL_SENT							BOOLEAN DEFAULT 0 NOT NULL
  ,ID_SALES_ORG_CREATION				INT NULL
  ,ID_TASK_EXECUTOR_TYPE				INT NULL
)