 CREATE TABLE TSM_TASK_EXECUTOR_TYPE
(
   ID_TASK_EXECUTOR_TYPE   INT PRIMARY KEY
  ,DS_TASK_EXECUTOR_TYPE   NVARCHAR(100) NOT NULL
  ,FL_ACTIVE			   BOOLEAN DEFAULT 0 NOT NULL
  ,FL_DEFAULT			   BOOLEAN DEFAULT 0 NOT NULL
)