CREATE TABLE TSM_ACTIVITY_DATE_CUSTOMER
(
   ID_ACTIVITY_DATE_CUSTOMER INT PRIMARY KEY
  ,ID_ACTIVITY_DATE			 INT NOT NULL
  ,ID_CUSTOMER				 INT NOT NULL
  ,ID_VISIT					 INT NOT NULL	
  ,DS_UNIQUE_KEY       NVARCHAR(36)
  ,DS_ACTIVITY_DATE_UNIQUE_KEY       NVARCHAR(36)
  ,VR_FL_SENT          BOOLEAN DEFAULT 0 NOT NULL
)