CREATE TABLE TSM_CERTIFICATION_POINT
(
   ID_ACTIVITY_DATE		   INT NOT NULL
  ,ID_SURVEY			   INT NOT NULL 
  ,ID_QUESTION			   INT NOT NULL
  ,MT_POINT				   DECIMAL NOT NULL
  ,MT_PERCENT			   DECIMAL NOT NULL
  ,DS_UNIQUE_KEY		   NVARCHAR(36)
  ,DS_ACTIVITY_DATE_UNIQUE_KEY		   NVARCHAR(36)
  ,VR_FL_SENT			   INT default 0
)