CREATE TABLE TSM_ACTIVITY_DATE
(
   ID_ACTIVITY_DATE			INT PRIMARY KEY
  ,ID_ACTIVITY				INT NULL
  ,DT_ACTIVITY         		DATETIME NOT NULL
  ,DT_DAY_START				DATETIME NULL
  ,DT_DAY_END				DATETIME NULL
  ,VR_FL_SENT				BOOLEAN DEFAULT 0 NOT NULL
  ,DS_UNIQUE_KEY			NVARCHAR(36)
  ,DS_ACTIVITY_UNIQUE_KEY   NVARCHAR(36)
  ,FL_FROM_WEB              BOOLEAN DEFAULT 0 NOT NULL
  ,VALID					BOOLEAN NULL
)