CREATE TABLE TSM_ACTIVITY_MEMBER
(
   ID_ACTIVITY_MEMBER		INT PRIMARY KEY 
  ,ID_ACTIVITY				INT NULL
  ,ID_USER					INT NULL
  ,DS_COMMENT				NVARCHAR(100) NULL
  ,DS_UNIQUE_KEY			NVARCHAR(36)
  ,DS_ACTIVITY_UNIQUE_KEY   NVARCHAR(36)
  ,VR_FL_SENT				BOOLEAN DEFAULT 0 NOT NULL
  ,FL_FROM_WEB              BOOLEAN DEFAULT 0 NOT NULL
  ,VALID					BOOLEAN NULL
)