CREATE TABLE TSM_ACTIVITY
(
   ID_ACTIVITY                     INT PRIMARY KEY
  ,DT_INSERT                       DATETIME NOT NULL
  ,ID_USER_INSERT                  INT NOT NULL
  ,DT_UPDATE                       DATETIME NOT NULL
  ,ID_USER_UPDATE                  INT NOT NULL
  ,VALID                           BOOLEAN NULL
  ,ID_COMPANY                      INT NOT NULL
  ,ID_USER                         INT NOT NULL
  ,ID_AGENT                        INT NULL
  ,ID_ACTIVITY_TYPE                INT NOT NULL
  ,DT_ACTIVITY_START               DATETIME NULL
  ,DT_ACTIVITY_END                 DATETIME NULL
  ,ID_ACTIVITY_STATUS              INT NOT NULL
  ,ID_ACTIVITY_SUBJECT             INT NULL
  ,ID_USER_APPROVAL                INT NULL
  ,DT_APPROVAL                     DATETIME NULL
  ,DS_COMMENT                      NVARCHAR(100) NULL
  ,VR_FL_SENT                      BOOLEAN DEFAULT 0 NOT NULL
  ,DS_UNIQUE_KEY                   NVARCHAR(100) NULL
  ,FL_FROM_WEB                     BOOLEAN DEFAULT 0 NOT NULL
  ,ID_SURVEY_GENERAL_REQUIREMENT   INT
  ,ID_SURVEY_CUSTOMER_ACTIVITY     INT
  ,ID_CERTIFICATION_TYPE           INT
  ,ID_SURVEY_EMPLOYEE_ASSESSMENT   INT
  ,ID_SURVEY_CR_PERFORMANCE        INT
  ,ID_SURVEY_HEALTH_SECURITY       INT
)