
CREATE TABLE TSM_TASK_CUSTOMER
(
   ID_TASK_CUSTOMER           INT PRIMARY KEY
  ,VALID					  BOOLEAN DEFAULT 1 NOT NULL
  ,ID_TASK                    INT NOT NULL
  ,ID_CUSTOMER                INT NOT NULL
  ,ID_TASK_EXECUTION_STATUS   INT NOT NULL
  ,ID_USER_COMPLETED          INT NULL
  ,DT_COMPLETED               DATETIME NULL
  ,ID_USER_APPROVED           INT NULL
  ,DT_APPROVED                DATETIME NULL
  ,DS_COMMENT				  NVARCHAR(250) NULL
  ,ID_TASK_INCOMPLETION_REASON   INT NULL
  ,ID_TASK_APPROVAL_STATUS    INT NULL
  ,DS_UNIQUE_KEY              NVARCHAR(36) NOT NULL 
  ,FL_WEB                     BOOLEAN DEFAULT 0 NOT NULL
  ,VR_FL_SENT                 BOOLEAN DEFAULT 0 NOT NULL
)