CREATE TABLE TSM_ACTIVITY_COMMENT
(
  ID_ACTIVITY_COMMENT INT PRIMARY KEY
  ,ID_ACTIVITY         INT
  ,ID_ACTIVITY_DATE    INT
  ,ID_COMMENT_TYPE     INT
  ,ID_COMMENT_TARGET   INT
  ,DS_COMMENT          NVARCHAR(500)
  ,VALID               BOOLEAN NOT NULL
  ,DS_UNIQUE_KEY       NVARCHAR(36)
  ,DS_ACTIVITY_UNIQUE_KEY       NVARCHAR(36)
  ,DS_ACTIVITY_DATE_UNIQUE_KEY   NVARCHAR(36)
  ,VR_FL_SENT          BOOLEAN DEFAULT 0 NOT NULL
)