CREATE TABLE TSM_ACTIVITY_SUBJECT
(
   ID_ACTIVITY_SUBJECT		INT PRIMARY KEY
  ,DT_INSERT         		DATETIME NOT NULL
  ,ID_USER_INSERT			INT NOT NULL
  ,DT_UPDATE				DATETIME NOT NULL
  ,ID_USER_UPDATE			INT NOT NULL
  ,VALID					BOOLEAN NULL
  ,FL_ACTIVE				BOOLEAN NULL
  ,ID_COMPANY				INT NOT NULL
  ,DS_ACTIVITY_SUBJECT		NVARCHAR(100) NULL
)