CREATE TABLE VDO_ATTRIBUTE
(
   ID_ATTRIBUTE				INT PRIMARY KEY
  ,ID_DEALER				INT NULL
  ,DS_ATTRIBUTE				NVARCHAR(50) NULL
  ,ID_DOCUMENT_TYPE			INT NULL
  ,ID_DATA_TYPE				INT NULL
  ,FL_MANDATORY	            BOOLEAN NULL
)