CREATE TABLE VDO_TRANSACTION_PRODUCT
(
   ID_TRANSACTION_PRODUCT		INT PRIMARY KEY
  ,ID_TRANSACTION				INT NULL
  ,ID_PRODUCT					INT NULL
  ,MT_QUANTITY					NUMERIC(8) NULL
  ,ID_UNIT						INT NULL
  ,VALID						BOOLEAN DEFAULT 0
  ,DS_UNIQUE_KEY				NVARCHAR(36) NOT NULL
)