CREATE TABLE VDO_DOCUMENT_TYPE
(
   ID_DOCUMENT_TYPE			INT PRIMARY KEY
  ,DS_DOCUMENT_TYPE         NVARCHAR(100) NULL
  ,DS_DOCUMENT_CODE         NVARCHAR(15) NULL
  ,FL_REQUIRES_SKU	        BOOLEAN DEFAULT 0
)